name: Deploy to AWS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
        with:
          node-version: '14' 

      - name: Install dependencies
        run: npm install

      - name: Build NestJS Application
        run: npm run build

      - name: Deploy to EC2 instance
      run: |
        scp -o StrictHostKeyChecking=no -r ./dist ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/hello-world-app/dist
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} 'cd /home/ubuntu/hello-world-app && npm install --only=production && pm2 start dist/main.js'

    - name: Post deployment cleanup
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} 'rm -rf /home/ubuntu/hello-world-app/node_modules'
