name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Prepare SSH
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts

      - name: Deploy to EC2
        env:
          REMOTE_HOST: ${{ secrets.EC2_HOST }}
          REMOTE_USER: ${{ secrets.EC2_USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          REMOTE_PORT: 22

        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

          ssh-keyscan -H $REMOTE_HOST >> ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts

          scp -i private_key.pem -r * $REMOTE_USER@$REMOTE_HOST:/home/$REMOTE_USER/pearlthoughts-first-task-hello-world

          ssh -i private_key.pem $REMOTE_USER@$REMOTE_HOST << 'EOF'
            cd /home/$REMOTE_USER/pearlthoughts-first-task-hello-world
            npm install
            pm2 stop all || true
            pm2 start dist/main.js --name "pearlthoughts-first-task-hello-world"
          EOF
